# Generated by Django 5.1.1 on 2025-07-28 08:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='アプリ名')),
                ('description', models.TextField(verbose_name='説明')),
                ('app_type', models.CharField(choices=[('image_classification', '画像分類'), ('object_detection', '物体検知'), ('text_classification', 'テキスト分類'), ('sentiment_analysis', '感情分析')], default='image_classification', max_length=50, verbose_name='アプリタイプ')),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True, verbose_name='推論エンドポイント')),
                ('model_file_path', models.CharField(blank=True, max_length=300, null=True, verbose_name='モデルファイルパス')),
                ('classes', models.JSONField(default=list, verbose_name='分類クラス一覧')),
                ('device_type', models.CharField(choices=[('auto', '自動選択'), ('cuda', 'CUDA (GPU)'), ('cpu', 'CPU'), ('mps', 'MPS (Apple Silicon)')], default='auto', max_length=20, verbose_name='推論デバイス')),
                ('batch_size', models.PositiveIntegerField(default=1, verbose_name='バッチサイズ')),
                ('use_mixed_precision', models.BooleanField(default=False, verbose_name='混合精度使用')),
                ('model_optimization', models.JSONField(default=dict, verbose_name='モデル最適化設定')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLアプリ',
                'verbose_name_plural': 'MLアプリ',
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(verbose_name='入力データ')),
                ('output_data', models.JSONField(verbose_name='出力データ')),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='信頼度')),
                ('predicted_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='予測クラス')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='処理時間（秒）')),
                ('user_feedback', models.CharField(blank=True, choices=[('correct', '正解'), ('incorrect', '不正解')], max_length=20, null=True, verbose_name='ユーザーフィードバック')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ml_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inference.mlapp', verbose_name='MLアプリ')),
            ],
            options={
                'verbose_name': '推論ログ',
                'verbose_name_plural': '推論ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='アップロード画像')),
                ('original_filename', models.CharField(max_length=255, verbose_name='元ファイル名')),
                ('file_size', models.PositiveIntegerField(verbose_name='ファイルサイズ（バイト）')),
                ('image_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='画像幅')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='画像高さ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inference.predictionlog', verbose_name='推論ログ')),
            ],
            options={
                'verbose_name': '画像アップロード',
                'verbose_name_plural': '画像アップロード',
            },
        ),
    ]
